apiVersion: apps/v1
kind: Deployment
metadata:
  name: SirenOrder
  labels:
    app: SirenOrder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SirenOrder
  template:
    metadata:
      labels:
        app: SirenOrder
    spec:
      containers:
        - name: SirenOrder
          image: username/SirenOrder:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5